
\ 6 ^ 4 =  1296 = 162 bytes

\ 1111 = 0
\ 1112 = 1
\ … 
\ 1116 = 5
\ 1121 = 6
\ …
\ 1126 = 11

6 CONSTANT MAXCOLOR
1296 CONSTANT MAXCODEWORDS
MAXCODEWORDS 8 / CONSTANT SETSIZE

: INDEX>CODEWORD ( i -- n )
    MAXCOLOR /MOD MAXCOLOR /MOD MAXCOLOR /MOD
    0 4 0 DO 10 * SWAP 1+ + LOOP ;

: CODEWORD>INDEX ( n -- i )
    10 /MOD 10 /MOD 10 /MOD
    0 4 0 DO MAXCOLOR * SWAP 1- + LOOP ;


: MATCHES ( cw,tw -- n )
    0 -ROT
    4 0 DO
        10 /MOD SWAP ROT
        10 /MOD SWAP ROT
        = IF ROT 1+ -ROT THEN
    LOOP 2DROP ;

CREATE SECRET-COLORS 7 ALLOT
CREATE TEST-COLORS 7 ALLOT

: TALLY-COLORS ( cw,addr -- )
    >R R@ 7 ERASE
    10 /MOD SWAP R@ + 1 SWAP +!
    10 /MOD SWAP R@ + 1 SWAP +!
    10 /MOD SWAP R@ + 1 SWAP +!
    R> + 1 SWAP +! ;

: HITS ( cw,tw -- n )
    TEST-COLORS TALLY-COLORS
    SECRET-COLORS TALLY-COLORS
    0 MAXCOLOR 1+ 1 DO
        SECRET-COLORS I + C@
        TEST-COLORS I + C@ MIN +
    LOOP ;

: MISSES ( cw,tw -- n )
    2DUP HITS -ROT MATCHES - ;

: MATCH ( cw,tw -- bw )
    2DUP MATCHES 10 * -ROT
    MISSES + ;

15 CONSTANT MAXRESULT
CREATE RESULT-VALUES
04 C, 03 C, 02 C, 01 C, 00 C, 13 C, 12 C, 11 C, 10 C, 22 C, 21 C, 20 C, 31 C, 30 C, 40 C,

: RESULT-INDEX ( bw -- n )
    0 SWAP
    MAXRESULT 0 DO
        DUP RESULT-VALUES I + C@ = IF
            NIP I SWAP LEAVE
        THEN
    LOOP DROP ;
        
