
\ 6 ^ 4 =  1296 = 162 bytes

\ 1111 = 0
\ 1112 = 1
\ … 
\ 1116 = 5
\ 1121 = 6
\ …
\ 1126 = 11

6 CONSTANT MAXCOLOR
1296 CONSTANT MAXCODEWORDS
MAXCODEWORDS 8 / CONSTANT SETSIZE

: INDEX>CODEWORD ( i -- n )
    MAXCOLOR /MOD MAXCOLOR /MOD MAXCOLOR /MOD
    0 4 0 DO 10 * SWAP 1+ + LOOP ;

: CODEWORD>INDEX ( n -- i )
    10 /MOD 10 /MOD 10 /MOD
    0 4 0 DO MAXCOLOR * SWAP 1- + LOOP ;


: CODEWORD-SET
    CREATE 0 , SETSIZE ALLOT ;

: INITSET ( addr -- )
    0 OVER !
    CELL+ SETSIZE 255 FILL ;

: NEXT-CODEWORD ( set -- cw,f )
    >R R@ @ 8 /MOD
    R@ CELL+ + C@
    2 ROT LSHIFT AND IF
        R@ @ INDEX>CODEWORD TRUE
        1 R> +!
    1 R> +! ;

: ELIMINATE-CODEWORD ( cw,set -- )
    SWAP CODEWORD>INDEX 8 /MOD
    ROT CELL+ + >R 
    2 SWAP LSHIFT 255 XOR
    R@ C@ AND R> C! ;
