REQUIRE random.fs

6 CONSTANT MAX-COLORS
4 CONSTANT MAX-PEGS

: POWER ( n,m -- n^m )
        1 SWAP 0 DO OVER * LOOP NIP ;

6 4 POWER CONSTANT MAX-CODEWORDS

: INDEX>CODEWORD ( i -- n )
    MAX-PEGS 1- 0 DO MAX-COLORS /MOD LOOP
    0 MAX-PEGS 0 DO 10 * SWAP 1+ + LOOP ;

: CODEWORD>INDEX ( n -- i )
    MAX-PEGS 1- 0 DO 10 /MOD LOOP
    0 MAX-PEGS 0 DO MAX-COLORS * SWAP 1- + LOOP ;

: CODE-SET ( <nnn> )
    CREATE 0 , MAX-CODEWORDS 8 / ALLOT ;

: INIT-SET ( set -- )
    CELL+ MAX-CODEWORDS 8 / 255 FILL ;

: EMPTY-SET ( set -- )
    CELL+ MAX-CODEWORDS 8 / ERASE ;

: START-SET ( set -- )
    -1 SWAP ! ;

: VALID-CODEWORD? ( set -- f )
    DUP CELL+ SWAP @ 8 /MOD ROT + C@ 1 ROT LSHIFT AND ;

: (NEXT-CODEWORD) ( set -- )
    BEGIN
        DUP 1 SWAP +!
        DUP @ MAX-CODEWORDS <
        OVER VALID-CODEWORD? 0= AND WHILE
    REPEAT DROP ;

: NEXT-CODEWORD ( set -- n|0 )
    DUP (NEXT-CODEWORD)
    @ DUP MAX-CODEWORDS < IF
        INDEX>CODEWORD
    ELSE
        DROP 0
    THEN ;

: CODEWORD-OFFSET ( cw,set -- addr )
    CELL+ SWAP CODEWORD>INDEX 8 /MOD ROT + ;

: CODEWORD-BITSET ( addr -- bs )
    C@ ROT 1 SWAP LSHIFT ;

: INSERT-CODEWORD ( cw,set -- )
    CODEWORD-OFFSET
    DUP CODEWORD-BITSET
    OR SWAP C! ;

: REMOVE-CODEWORD ( cw,set -- )
    CODEWORD-OFFSET
    DUP CODEWORD-BITSET
    255 XOR AND SWAP C! ;

DEFER DO-WITH-CODEWORD

: COUNT-CODEWORD ( n,set,cw -- n',set )
    DROP SWAP 1+ SWAP ;

: SET-ITERATE ( set -- )
    DUP START-SET
    BEGIN
        DUP NEXT-CODEWORD ?DUP WHILE
        DO-WITH-CODEWORD
    REPEAT DROP ;

: SET-SIZE ( set -- n )
    ['] COUNT-CODEWORD IS DO-WITH-CODEWORD
    0 SWAP SET-ITERATE ;

: .CODEWORD ( cw -- )
    . ;

: .SET ( set -- )
    ['] .CODEWORD IS DO-WITH-CODEWORD
    SET-ITERATE ;

: MATCHES ( cw,tw -- n )
    0 -ROT
    MAX-PEGS 0 DO
        10 /MOD SWAP ROT
        10 /MOD SWAP ROT
        = IF ROT 1+ -ROT THEN
    LOOP 2DROP ;

CREATE TALLY MAX-COLORS 2* ALLOT
TALLY MAX-COLORS + CONSTANT TALLY-TEST

: TALLY-RESET
    TALLY MAX-COLORS 2* ERASE ;

: HITS ( cw,tw -- n )
    TALLY-RESET
    MAX-PEGS 1- 0 DO 10 /MOD LOOP
    MAX-PEGS 0 DO 1- TALLY-TEST + DUP C@ 1+ SWAP C! LOOP
    MAX-PEGS 1- 0 DO 10 /MOD LOOP
    MAX-PEGS 0 DO 1- TALLY + DUP C@ 1+ SWAP C! LOOP
    0 MAX-COLORS 0 DO
        TALLY I + C@
        TALLY-TEST I + C@ MIN +
    LOOP ;

: MISSES ( cw,tw -- n )
    2DUP HITS -ROT MATCHES - ;

: MATCH ( cw,tw -- bw )
    2DUP MISSES -ROT
    MATCHES 10 * + ;

VARIABLE SOURCE-SET
VARIABLE TARGET-SET

: RESULT-MATCH-DO ( cw,r,set,cw' -- cw,r,set )
    DUP >R
    2OVER                   \ cw,r,set,cw',cw,r
    -ROT MATCH              \ cw,r,set,r,r'
    = IF
        R> TARGET-SET @ INSERT-CODEWORD
    ELSE
        R> DROP
    THEN ;

: RESULT-MATCH-SET ( cw,r,srce,dest )
    TARGET-SET !  SOURCE-SET !
    TARGET-SET @ EMPTY-SET
    ['] RESULT-MATCH-DO IS DO-WITH-CODEWORD
    SOURCE-SET @ SET-ITERATE 2DROP ;

: COPY-SET-DO ( cw -- )
    TARGET-SET @ INSERT-CODEWORD ;

: COPY-SET ( srce,dest -- )
    TARGET-SET !  SOURCE-SET !
    TARGET-SET @ EMPTY-SET
    ['] COPY-SET-DO IS DO-WITH-CODEWORD
    SOURCE-SET @ SET-ITERATE ;

CREATE RESULT-VALUES 04 C, 03 C, 02 C, 01 C, 00 C, 13 C, 12 C, 11 C, 10 C, 22 C, 21 C, 20 C, 31 C, 30 C, 40 C, 

: RESULT-VALUE ( n -- v )
    RESULT-VALUES + C@ ;

: RESULT-INDEX ( r -- n )
    -1 SWAP
    15 0 DO DUP I RESULT-VALUE = IF
        2DROP I I LEAVE
    THEN
    LOOP DROP ;


CREATE RESULT-SETS
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT
0 , MAX-CODEWORDS 8 / ALLOT

: RESULT-SET ( n -- set )
    ASSERT( DUP 0 15 WITHIN )
    MAX-CODEWORDS 8 / CELL+ * RESULT-SETS + ;

: ALL-RESULTS-MATCH ( cw,srce -- )
    15 0 DO
        2DUP I RESULT-VALUE
        SWAP I RESULT-SET    \ cw,srce,cw,r,srce,dest
        RESULT-MATCH-SET
    LOOP 2DROP ;

: ALL-RESULTS-MAX ( -- n )
    0 15 0 DO I RESULT-SET SET-SIZE MAX LOOP ;

: .RESULT ( r -- )
    DUP 0= IF
        ." __" DROP
    ELSE
        10 /MOD 
        0 ?DO ." ●" LOOP
        0 ?DO ." ○" LOOP
    THEN ;

: .ALL-RESULTS
    15 0 DO
        I 2 .R [CHAR] ) EMIT SPACE I RESULT-VALUE .RESULT SPACE
        I RESULT-SET DUP SET-SIZE . .SET CR
    LOOP
    0 15 0 DO I RESULT-SET SET-SIZE MAX LOOP
    ." max = " . cr ;

    1111 VALUE SECRET

: NEW-SECRET
    1296 RANDOM INDEX>CODEWORD TO SECRET ;

CODE-SET POSSIBLE-CODES
POSSIBLE-CODES INIT-SET
VARIABLE GUESS

VARIABLE COUNTER

: GUESS-CODEWORD
    CR
    POSSIBLE-CODES INIT-SET 
    COUNTER OFF
    1122 GUESS !
    BEGIN
        1 COUNTER +!  COUNTER ?
        GUESS @ . [CHAR] : EMIT SPACE
        GUESS @ POSSIBLE-CODES ALL-RESULTS-MATCH
        15 0 DO I RESULT-VALUE .RESULT SPACE I RESULT-SET SET-SIZE . [CHAR] , EMIT SPACE LOOP CR
        POSSIBLE-CODES DUP SET-SIZE 1 > WHILE
        SECRET GUESS @ MATCH DUP .RESULT CR
        RESULT-INDEX RESULT-SET POSSIBLE-CODES COPY-SET
        DUP START-SET NEXT-CODEWORD GUESS !
    REPEAT ;

CODE-SET ALL-CODES-SET

VARIABLE MIN-MAX-RESULT
VARIABLE MIN-MAX-CODEWORD
VARIABLE POSSIBLE-CODE

: MIN-MAX-ALL-RESULT-MATCH ( -- cw )
    ALL-CODES-SET INIT-SET
    10000 MIN-MAX-RESULT !
    0 MIN-MAX-CODEWORD
    POSSIBLE-CODES START-SET
    BEGIN
        POSSIBLE-CODES NEXT-CODEWORD ?DUP WHILE
        POSSIBLE-CODE !
        POSSIBLE-CODE @ ALL-CODES-SET ALL-RESULTS-MATCH
        ALL-RESULTS-MAX 
        MIN-MAX-RESULT @ OVER > IF
            MIN-MAX-RESULT !
            POSSIBLE-CODE @ MIN-MAX-CODEWORD !
        ELSE
            DROP
        THEN
    REPEAT MIN-MAX-CODEWORD @ ;

: GUESS-BETTER ( -- cw )
    POSSIBLE-CODES INIT-SET
    COUNTER OFF
    1122 GUESS !
    CR
    BEGIN
        1 COUNTER +! COUNTER ?
        GUESS @ . [CHAR] : EMIT SPACE
        GUESS @ SECRET MATCH DUP .RESULT CR
        DUP 40 <> WHILE
        GUESS @ POSSIBLE-CODES ALL-RESULTS-MATCH
        RESULT-INDEX RESULT-SET POSSIBLE-CODES COPY-SET
        MIN-MAX-ALL-RESULT-MATCH GUESS !
    REPEAT ;
     
UTIME DROP SEED !
NEW-SECRET

: START-GUESSING 
    ." think of a secret code of 4 digits with digits 1,2,3,4,5 or 6" CR
    POSSIBLE-CODES INIT-SET
    1 COUNTER !
    1122 GUESS !
    ." my first guess is " GUESS ? CR
    ." type " 15 0 DO I RESULT-VALUE . LOOP ." followed by !!" CR ;

: !!
    RESULT-INDEX
    DUP -1 = IF
        DROP
        ." incorrect result value, try again with one of these values: " 15 0 DO I RESULT-VALUE . LOOP ." followed by !!" CR
        DROP
    ELSE DUP 14 = IF
        DROP
        ." found in " COUNTER ? ." moves !"
    ELSE
        GUESS @ POSSIBLE-CODES ALL-RESULTS-MATCH
        RESULT-SET POSSIBLE-CODES COPY-SET
        MIN-MAX-ALL-RESULT-MATCH GUESS !
        1 COUNTER +!
        ." my next guess is " GUESS ? CR
    THEN THEN ;
